// Player variant C — WAVY + VERTICAL EYES.  **LOCKED as the main character.**
//
// 16 x 32 px, actual Stardew Valley sprite scale.
//
// Each facing supplies rows 0..22 only: head, torso and arms. Rows 23..31 come
// from art/player/walk-legs.mjs, so a walk frame is (body + leg block), and the
// legs are authored once instead of once per facing.
//
// Hair reads wavy through three cues at once, none sufficient alone at 16px:
//   1. the mass bulges to 14px against a 12px head — volume
//   2. the hairline curves rather than sitting level
//   3. DETAIL pins two S-curved highlight strands with a shadow crown between
//
//   R hair   K skin   I eye   M mouth
//   J jacket   j sleeve   C shirt   V red tie
//   P trousers   S shoe   L sole

export const NAME = 'c';
export const LABEL = 'WAVY + VERTICAL EYES';
export const W = 16, H = 32;
export const BODY_ROWS = 23;   // rows 0..22; legs are composed in

export const DOWN = [
  '................', //  0
  '.....RRRRRR.....', //  1
  '...RRRRRRRRRR...', //  2
  '..RRRRRRRRRRRR..', //  3
  '.RRRRRRRRRRRRRR.', //  4
  '.RRRRRRRRRRRRRR.', //  5
  '.RRRRRRRRRRRRRR.', //  6
  '.RRRRKKKRRKKKRR.', //  7
  '..RRKIKKKKIKRR..', //  8
  '..RRKIKKKKIKRR..', //  9
  '.RRRKKKKKKKKRRR.', // 10
  '...RKKKMMKKKR...', // 11
  '.....KKKKKK.....', // 12
  '...JJCCVVCCJJ...', // 13
  '..JJJCCVVCCJJJ..', // 14
  '.jjjJCCVVCCJjjj.', // 15
  '.jjjJCCVVCCJjjj.', // 16
  '.jjjJJCVVCJJjjj.', // 17
  '.jjjJJCCCCJJjjj.', // 18
  '.jjjJJJCCJJJjjj.', // 19
  '.KKjJJJJJJJJjKK.', // 20
  '.KKjJJJJJJJJjKK.', // 21
  '...JJJJJJJJJJ...', // 22
];

export const DOWN_DETAIL = [
  '................',
  '................',
  '................',
  '....77....77....',
  '...77......77...',
  '...7..2222..7...',
  '....7.2222.7....',
  '..7.........7...',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
];

export const UP = [
  '................', //  0
  '.....RRRRRR.....', //  1
  '...RRRRRRRRRR...', //  2
  '..RRRRRRRRRRRR..', //  3
  '.RRRRRRRRRRRRRR.', //  4
  '.RRRRRRRRRRRRRR.', //  5
  '.RRRRRRRRRRRRRR.', //  6
  '.RRRRRRRRRRRRRR.', //  7
  '..RRRRRRRRRRRR..', //  8
  '..RRRRRRRRRRRR..', //  9
  '.RRRRRRRRRRRRRR.', // 10
  '..RRRRRRRRRRRR..', // 11
  '....RRRRRRRR....', // 12
  '...JJJCCCCJJJ...', // 13
  '..JJJJCCCCJJJJ..', // 14
  '.jjjJJJJJJJJjjj.', // 15
  '.jjjJJJJJJJJjjj.', // 16
  '.jjjJJJJJJJJjjj.', // 17
  '.jjjJJJJJJJJjjj.', // 18
  '.jjjJJJJJJJJjjj.', // 19
  '.KKjJJJJJJJJjKK.', // 20
  '.KKjJJJJJJJJjKK.', // 21
  '...JJJJJJJJJJ...', // 22
];

export const UP_DETAIL = [
  '................',
  '................',
  '................',
  '....77....77....',
  '...77......77...',
  '...7..2222..7...',
  '....7.2222.7....',
  '..7.........7...',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
];

export const SIDE = [
  '................', //  0
  '.....RRRRRR.....', //  1
  '....RRRRRRRR....', //  2
  '...RRRRRRRRRR...', //  3
  '...RRRRRRRRRR...', //  4
  '...RRRRRRRRRR...', //  5
  '...RRRRRRRRRR...', //  6
  '...RRRRRRKKKK...', //  7
  '...RRRRRKIKKK...', //  8
  '...RRRRRKIKKKK..', //  9
  '...RRRRRKKKKK...', // 10
  '....RRRKKKKKM...', // 11
  '.....RRKKKKKK...', // 12
  '...JJJJJJCVCJ...', // 13
  '..JJJJJJJCVCJ...', // 14
  '..jjJJJJJCVCJ...', // 15
  '..jjJJJJJCVCJ...', // 16
  '..jjJJJJJJVCJ...', // 17
  '..jjJJJJJJCCJ...', // 18
  '..jjJJJJJJJJJ...', // 19
  '..KKJJJJJJJJJ...', // 20
  '..KKJJJJJJJJJ...', // 21
  '...JJJJJJJJJ....', // 22
];

export const SIDE_DETAIL = [
  '................',
  '................',
  '................',
  '.....77..77.....',
  '....77....77....',
  '....7..22..7....',
  '.....7.22.7.....',
  '................',
  '................',
  '................',
  '...........2....',
  '........22......',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
];

// SIDE faces screen-right; LEFT is generated by mirroring it at build time.

// Arm swing for the profile walk. Each entry patches body rows 19-21 for one
// walk frame: neutral, swung forward, neutral, swung back. Front and back
// facings have no equivalent — an arm swinging toward or away from the camera
// barely changes the silhouette, so only the profile needs it.
export const SIDE_ARMS = [
  { 19: '..jjJJJJJJJJJ...', 20: '..KKJJJJJJJJJ...', 21: '..KKJJJJJJJJJ...' },
  { 19: '..JjjJJJJJJJJ...', 20: '..JKKJJJJJJJJ...', 21: '..JJJJJJJJJJJ...' },
  { 19: '..jjJJJJJJJJJ...', 20: '..KKJJJJJJJJJ...', 21: '..KKJJJJJJJJJ...' },
  { 19: '.jjJJJJJJJJJJ...', 20: '.KKJJJJJJJJJJ...', 21: '.KKJJJJJJJJJJ...' },
];

export const ARMS = { side: SIDE_ARMS };

export const BODIES = { down: DOWN, up: UP, side: SIDE };
export const DETAILS = { down: DOWN_DETAIL, up: UP_DETAIL, side: SIDE_DETAIL };
